server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/library_management?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.Mtsql5Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  devtools:
    livereload:
      enabled: true


